#!/usr/bin/env bash
set -euo pipefail

echo "Initializing databases for Moodle and Keycloak..."

MOODLE_DB_NAME="${MOODLE_DB_NAME:-moodle}"
MOODLE_DB_USER="${MOODLE_DB_USER:-moodle}"
MOODLE_DB_PASSWORD="${MOODLE_DB_PASSWORD:-moodlepass}"

KEYCLOAK_DB_NAME="${KEYCLOAK_DB_NAME:-keycloak}"
KEYCLOAK_DB_USER="${KEYCLOAK_DB_USER:-keycloak}"
KEYCLOAK_DB_PASSWORD="${KEYCLOAK_DB_PASSWORD:-keycloakpass}"

POSTGRES_MONITOR_USER="${POSTGRES_MONITOR_USER:-monitoring}"
POSTGRES_MONITOR_PASSWORD="${POSTGRES_MONITOR_PASSWORD:-monitoringpass}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${MOODLE_DB_USER}') THEN
      CREATE ROLE ${MOODLE_DB_USER} LOGIN PASSWORD '${MOODLE_DB_PASSWORD}';
   END IF;
END
\$\$;

DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${KEYCLOAK_DB_USER}') THEN
      CREATE ROLE ${KEYCLOAK_DB_USER} LOGIN PASSWORD '${KEYCLOAK_DB_PASSWORD}';
   END IF;
END
\$\$;

DO \$\$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${POSTGRES_MONITOR_USER}') THEN
      CREATE ROLE ${POSTGRES_MONITOR_USER} LOGIN PASSWORD '${POSTGRES_MONITOR_PASSWORD}';
   END IF;
END
\$\$;

CREATE DATABASE ${MOODLE_DB_NAME} OWNER ${MOODLE_DB_USER};
CREATE DATABASE ${KEYCLOAK_DB_NAME} OWNER ${KEYCLOAK_DB_USER};

GRANT ALL PRIVILEGES ON DATABASE ${MOODLE_DB_NAME} TO ${MOODLE_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${KEYCLOAK_DB_NAME} TO ${KEYCLOAK_DB_USER};

GRANT pg_monitor TO ${POSTGRES_MONITOR_USER};
GRANT pg_read_all_data TO ${POSTGRES_MONITOR_USER};

-- Ensure monitoring role can read all schemas when created later.
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO ${POSTGRES_MONITOR_USER};
EOSQL

echo "Database initialization complete."
